# Generated by Django 3.1.4 on 2021-09-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('describe', models.TextField(max_length=200, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_image/')),
                ('date_add', models.DateField(verbose_name='date ajout')),
            ],
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('describe', models.TextField(max_length=200, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actu_image/')),
                ('date_add', models.DateField(verbose_name='date ajout')),
            ],
        ),
        migrations.CreateModel(
            name='Adherant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('firt_name', models.CharField(max_length=200, verbose_name='prenom')),
                ('adress', models.CharField(max_length=200, verbose_name='adress')),
                ('country', models.CharField(choices=[('CIVILITE', 'CIVILITE'), ('France', 'france'), ("Cote d'ivoire", "Cote d'ivoire"), ('Belgique', 'belgique')], max_length=200, verbose_name='pays')),
                ('city', models.CharField(default='', max_length=100, verbose_name='ville')),
                ('phone', models.IntegerField(default=0, verbose_name='annee telephone')),
                ('civilite', models.CharField(choices=[('CIVILITE', 'CIVILITE'), ('Mr', 'M.'), ('MM', 'Mm.'), ('MLLE', 'Mlle.')], default='', max_length=200, verbose_name='civilité')),
                ('payer', models.BooleanField(default=False)),
                ('code_postal', models.IntegerField(default=0, max_length=20, verbose_name='code postal')),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('firt_name', models.CharField(max_length=200, verbose_name='prenom')),
                ('adress', models.CharField(max_length=200, verbose_name='adress')),
                ('country', models.CharField(max_length=200, verbose_name='pays')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='date ajout')),
                ('num_carte', models.IntegerField(verbose_name='numreo de carte')),
                ('cvv', models.IntegerField(verbose_name='code de securité')),
                ('morth', models.CharField(choices=[('JANVIER', 'JANVIER'), ('FEVRIER', 'Fevrier'), ('MARS', 'Mars'), ('AVRIL', 'Avril'), ('MAI', 'Mai'), ('JUIN', 'Juin'), ('JUILLER', 'Juiller'), ('AOUT', 'Aout'), ('SEPTEMBRE', 'Septembre'), ('OCTOBRE', 'Octobre'), ('NOVEMBRE', 'Novembre'), ('DECEMBRE', 'Decembre')], default='', max_length=30, verbose_name='mois cart')),
                ('years', models.IntegerField(choices=[('DEFAULT', 'CHOICE'), (2020, 2002), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default='', verbose_name='annee carte')),
                ('civilite', models.CharField(choices=[('CIVILITE', 'CIVILITE'), ('Mr', 'M.'), ('MM', 'Mm.'), ('MLLE', 'Mlle.')], default='', max_length=200, verbose_name='civilité')),
                ('money', models.IntegerField(verbose_name='somme payer')),
            ],
        ),
    ]
