# Generated by Django 3.1.4 on 2021-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_home', '0002_auto_20210913_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherant',
            name='country',
            field=models.CharField(choices=[('PAYS', 'PAYS'), ('France', 'France'), ("Cote d'ivoire", "Cote d'ivoire"), ('Belgique', 'belgique')], max_length=200, verbose_name='pays'),
        ),
    ]
