# Generated by Django 3.1.4 on 2021-09-13 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acs_home', '0004_auto_20210913_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='don',
            name='morth',
        ),
        migrations.RemoveField(
            model_name='don',
            name='num_carte',
        ),
        migrations.RemoveField(
            model_name='don',
            name='years',
        ),
        migrations.AlterField(
            model_name='don',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
