# Generated by Django 3.1.4 on 2021-09-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_home', '0007_don_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='don_image/'),
        ),
    ]
